name: re_reselect
description: Re-reselect is a lightweight wrapper around Reselect
version: 0.1.0
homepage: https://github.com/NevRA/re_reselect
author: Roman Abdulmanov <roman.abdulmanov@gmail.com>

environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'

dependencies:
  reselect: ^0.4.0

dev_dependencies:
  test: ^1.3.0

